__all__ = ['disjoint_union', 'union', 'intersection']

def disjoint_union(graphs): ...
def union(graphs, byname: str = 'auto'): ...
def intersection(graphs, byname: str = 'auto', keep_all_vertices: bool = True): ...
