__all__ = ['__iadd__', '__add__', '__and__', '__isub__', '__sub__', '__mul__', '__or__', '_disjoint_union', '_union', '_intersection']

def _disjoint_union(graph, other): ...
def _union(graph, other, byname: str = 'auto'): ...
def _intersection(graph, other, byname: str = 'auto'): ...
def __iadd__(graph, other): ...
def __add__(graph, other): ...
def __and__(graph, other): ...
def __isub__(graph, other): ...
def __sub__(graph, other): ...
def __mul__(graph, other): ...
def __or__(graph, other): ...
