import abc
from abc import abstractmethod
from igraph.drawing.cairo.base import AbstractCairoDrawer as AbstractCairoDrawer
from igraph.drawing.utils import BoundingBox as BoundingBox

class CoordinateSystem(AbstractCairoDrawer, metaclass=abc.ABCMeta):
    @abstractmethod
    def draw(self): ...
    @abstractmethod
    def local_to_context(self, x, y): ...

class DescartesCoordinateSystem(CoordinateSystem):
    def __init__(self, context, bbox, bounds) -> None: ...
    @property
    def bbox(self): ...
    @bbox.setter
    def bbox(self, bbox) -> None: ...
    @property
    def bounds(self): ...
    @bounds.setter
    def bounds(self, bounds) -> None: ...
    def draw(self) -> None: ...
    def local_to_context(self, x, y): ...
