from _typeshed import Incomplete

__all__ = ['CairoPlot']

class CairoPlot:
    bbox: Incomplete
    def __init__(self, target=None, bbox=None, palette=None, background=None) -> None: ...
    def add(self, obj, bbox=None, palette=None, opacity: float = 1.0, *args, **kwds) -> None: ...
    @property
    def background(self): ...
    @background.setter
    def background(self, color) -> None: ...
    def remove(self, obj, bbox=None, idx: int = 1): ...
    def mark_dirty(self) -> None: ...
    def redraw(self, context=None) -> None: ...
    def save(self, fname=None): ...
    @property
    def bounding_box(self): ...
    @property
    def height(self): ...
    @property
    def surface(self): ...
    @property
    def width(self): ...
