from .base import AbstractCairoDrawer

__all__ = ['CairoPolygonDrawer']

class CairoPolygonDrawer(AbstractCairoDrawer):
    def __init__(self, context, bbox=(1, 1)) -> None: ...
    def draw_path(self, points, corner_radius: int = 0) -> None: ...
    def draw(self, points) -> None: ...
