from _typeshed import Incomplete
from igraph.drawing.cairo.base import AbstractCairoDrawer

__all__ = ['CairoTextDrawer']

class CairoTextDrawer(AbstractCairoDrawer):
    LEFT: Incomplete
    CENTER: Incomplete
    RIGHT: Incomplete
    TOP: Incomplete
    BOTTOM: Incomplete
    halign: Incomplete
    valign: Incomplete
    def __init__(self, context, text: str = '', halign: str = 'center', valign: str = 'center') -> None: ...
    def draw(self, wrap: bool = False) -> None: ...
    def get_text_layout(self, x=None, y=None, width=None, wrap: bool = False): ...
    def draw_at(self, x=None, y=None, width=None, wrap: bool = False) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    def text_extents(self): ...
