from _typeshed import Incomplete
from igraph.drawing.baseclasses import AbstractEdgeDrawer
from igraph.drawing.utils import FakeModule

__all__ = ['MatplotlibEdgeDrawer', 'EdgeCollection']

PatchCollection = FakeModule

class MatplotlibEdgeDrawer(AbstractEdgeDrawer):
    context: Incomplete
    palette: Incomplete
    VisualEdgeBuilder: Incomplete
    def __init__(self, context, palette) -> None: ...
    def build_patch(self, edge, src_vertex, dest_vertex): ...
    def draw_directed_edge(self, edge, src_vertex, dest_vertex): ...
    def draw_undirected_edge(self, edge, src_vertex, dest_vertex): ...

class EdgeCollection(PatchCollection):
    def __init__(self, *args, **kwargs) -> None: ...
    def draw(self, renderer): ...
    def get_arrow_sizes(self): ...
    def get_arrow_size(self): ...
    def set_arrow_size(self, sizes) -> None: ...
    def set_arrow_sizes(self, sizes): ...
    def get_arrow_widths(self): ...
    def get_arrow_width(self): ...
    def set_arrow_width(self, widths) -> None: ...
    def set_arrow_widths(self, widths): ...
    @property
    def stale(self): ...
    @stale.setter
    def stale(self, val) -> None: ...
