from _typeshed import Incomplete
from igraph.drawing.baseclasses import AbstractGraphDrawer
from igraph.drawing.utils import FakeModule

__all__ = ['MatplotlibGraphDrawer']

Artist = FakeModule
Affine2D = FakeModule

class GraphArtist(Artist, AbstractGraphDrawer):
    graph: Incomplete
    kwds: Incomplete
    def __init__(self, graph, vertex_drawer_factory=..., edge_drawer_factory=..., mark_groups=None, layout=None, palette=None, **kwds) -> None: ...
    def get_children(self): ...
    def get_vertices(self): ...
    def get_edges(self): ...
    def get_groups(self): ...
    def get_vertex_labels(self): ...
    def get_edge_labels(self): ...
    def get_datalim(self): ...
    @_stale_wrapper
    def draw(self, renderer, *args, **kwds): ...
    def set(self, **kwds) -> None: ...
    def contains(self, mouseevent): ...
    def pick(self, mouseevent) -> None: ...

class MatplotlibGraphDrawer(AbstractGraphDrawer):
    ax: Incomplete
    vertex_drawer_factory: Incomplete
    edge_drawer_factory: Incomplete
    def __init__(self, ax, vertex_drawer_factory=..., edge_drawer_factory=...) -> None: ...
    def draw(self, graph, *args, **kwds): ...
