from _typeshed import Incomplete
from igraph.drawing.baseclasses import AbstractVertexDrawer
from igraph.drawing.utils import FakeModule

__all__ = ['MatplotlibVertexDrawer', 'VertexCollection']

IdentityTransform = FakeModule
PatchCollection = FakeModule

class MatplotlibVertexDrawer(AbstractVertexDrawer):
    context: Incomplete
    VisualVertexBuilder: Incomplete
    def __init__(self, ax, palette, layout) -> None: ...
    def draw(self, visual_vertex, vertex, coords): ...

class VertexCollection(PatchCollection):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_sizes(self): ...
    def get_size(self): ...
    def set_size(self, sizes) -> None: ...
    def set_sizes(self, sizes) -> None: ...
    @property
    def stale(self): ...
    @stale.setter
    def stale(self, val) -> None: ...
