from _typeshed import Incomplete
from abc import ABCMeta

__all__ = ['Palette', 'GradientPalette', 'AdvancedGradientPalette', 'RainbowPalette', 'PrecalculatedPalette', 'ClusterColoringPalette', 'color_name_to_rgb', 'color_name_to_rgba', 'hsv_to_rgb', 'hsva_to_rgba', 'hsl_to_rgb', 'hsla_to_rgba', 'rgb_to_hsv', 'rgba_to_hsva', 'rgb_to_hsl', 'rgba_to_hsla', 'palettes', 'default_edge_colors', 'known_colors']

class Palette(metaclass=ABCMeta):
    def __init__(self, n) -> None: ...
    def clear_cache(self) -> None: ...
    def get(self, v): ...
    def get_many(self, colors): ...
    __getitem__ = get
    @property
    def length(self): ...
    def __len__(self) -> int: ...
    def __plot__(self, backend, context, *args, **kwds) -> None: ...

class GradientPalette(Palette):
    def __init__(self, color1, color2, n: int = 256) -> None: ...

class AdvancedGradientPalette(Palette):
    def __init__(self, colors, indices=None, n: int = 256) -> None: ...

class RainbowPalette(Palette):
    def __init__(self, n: int = 256, s: int = 1, v: int = 1, start: int = 0, end: int = 1, alpha: int = 1) -> None: ...

class PrecalculatedPalette(Palette):
    def __init__(self, items) -> None: ...

class ClusterColoringPalette(PrecalculatedPalette):
    def __init__(self, n) -> None: ...

def color_name_to_rgb(color, palette=None): ...
def color_name_to_rgba(color, palette=None): ...
def hsla_to_rgba(h, s, l, alpha: float = 1.0): ...
def hsl_to_rgb(h, s, l): ...
def hsva_to_rgba(h, s, v, alpha: float = 1.0): ...
def hsv_to_rgb(h, s, v): ...
def rgba_to_hsla(r, g, b, alpha: float = 1.0): ...
def rgba_to_hsva(r, g, b, alpha: float = 1.0): ...
def rgb_to_hsl(r, g, b): ...
def rgb_to_hsv(r, g, b): ...

default_edge_colors: Incomplete
known_colors: Incomplete
palettes: Incomplete
