from _typeshed import Incomplete
from igraph.drawing.baseclasses import AbstractGraphDrawer, AbstractXMLRPCDrawer

__all__ = ['CytoscapeGraphDrawer', '__plot__']

class CytoscapeGraphDrawer(AbstractXMLRPCDrawer, AbstractGraphDrawer):
    network_id: Incomplete
    def __init__(self, url: str = 'http://localhost:9000/Cytoscape') -> None: ...
    def draw(self, graph, name: str = 'Network from igraph', create_view: bool = True, *args, **kwds) -> None: ...
    def fetch(self, name=None, directed: bool = False, keep_canonical_names: bool = False): ...
    @staticmethod
    def infer_cytoscape_type(values): ...

class GephiGraphStreamingDrawer(AbstractGraphDrawer):
    connection: Incomplete
    streamer: Incomplete
    def __init__(self, conn=None, *args, **kwds) -> None: ...
    def draw(self, graph, *args, **kwds) -> None: ...

def __plot__(self, backend, context, *args, **kwds): ...
