from typing import NamedTuple

__all__ = ['BoundingBox', 'Point', 'Rectangle', 'calculate_corner_radii', 'euclidean_distance', 'evaluate_cubic_bezier', 'get_bezier_control_points_for_curved_edge', 'intersect_bezier_curve_and_circle', 'str_to_orientation', 'autocurve']

class Rectangle:
    def __init__(self, *args) -> None: ...
    @property
    def coords(self): ...
    @coords.setter
    def coords(self, coords) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, value) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, value) -> None: ...
    @property
    def left(self): ...
    @left.setter
    def left(self, value) -> None: ...
    @property
    def right(self): ...
    @right.setter
    def right(self, value) -> None: ...
    @property
    def top(self): ...
    @top.setter
    def top(self, value) -> None: ...
    @property
    def bottom(self): ...
    @bottom.setter
    def bottom(self, value) -> None: ...
    @property
    def midx(self): ...
    @midx.setter
    def midx(self, value) -> None: ...
    @property
    def midy(self): ...
    @midy.setter
    def midy(self, value) -> None: ...
    @property
    def shape(self): ...
    @shape.setter
    def shape(self, shape) -> None: ...
    def contract(self, margins): ...
    def expand(self, margins): ...
    def isdisjoint(self, other): ...
    def isempty(self): ...
    def intersection(self, other): ...
    __and__ = intersection
    def translate(self, dx, dy) -> None: ...
    def union(self, other): ...
    __or__ = union
    def __ior__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __bool__(self) -> bool: ...
    def __hash__(self): ...

class BoundingBox(Rectangle):
    def __ior__(self, other): ...
    def __or__(self, other): ...

class FakeModule:
    def __init__(self, message) -> None: ...
    def __getattr__(self, _) -> None: ...
    def __call__(self, _) -> None: ...
    def __setattr__(self, key, value) -> None: ...

class Point(NamedTuple('_Point', [('x', float), ('y', float)])):
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, scalar): ...
    __rmul__ = __mul__
    def __div__(self, scalar): ...
    def as_polar(self): ...
    def distance(self, other): ...
    def interpolate(self, other, ratio: float = 0.5): ...
    def length(self): ...
    def normalized(self): ...
    def sq_length(self): ...
    def towards(self, other, distance: int = 0): ...
    @classmethod
    def FromPolar(cls, radius, angle): ...

def calculate_corner_radii(points, corner_radius): ...
def euclidean_distance(x1, y1, x2, y2): ...
def evaluate_cubic_bezier(x0, y0, x1, y1, x2, y2, x3, y3, t): ...
def get_bezier_control_points_for_curved_edge(x1, y1, x2, y2, curvature): ...
def intersect_bezier_curve_and_circle(x0, y0, x1, y1, x2, y2, x3, y3, radius, max_iter: int = 10): ...
def str_to_orientation(value, reversed_horizontal: bool = False, reversed_vertical: bool = False): ...
def autocurve(graph, attribute: str = 'curved', default: int = 0): ...
