import igraph
from _typeshed import Incomplete
from igraph import ARPACKOptions as ARPACKOptions, BFSIter as BFSIter, DFSIter as DFSIter, Edge as Edge, Vertex as Vertex
from typing import Any, overload

ADJ_DIRECTED: int
ADJ_LOWER: int
ADJ_MAX: int
ADJ_MIN: int
ADJ_PLUS: int
ADJ_UNDIRECTED: int
ADJ_UPPER: int
ALL: int
BLISS_F: int
BLISS_FL: int
BLISS_FLM: int
BLISS_FM: int
BLISS_FS: int
BLISS_FSM: int
GET_ADJACENCY_BOTH: int
GET_ADJACENCY_LOWER: int
GET_ADJACENCY_UPPER: int
IN: int
INTEGER_SIZE: int
LOOPS_SW: int
MULTI_SW: int
OUT: int
SIMPLE_SW: int
STAR_IN: int
STAR_MUTUAL: int
STAR_OUT: int
STAR_UNDIRECTED: int
STRONG: int
TRANSITIVITY_NAN: int
TRANSITIVITY_ZERO: int
TREE_IN: int
TREE_OUT: int
TREE_UNDIRECTED: int
WEAK: int
__build_date__: str
__igraph_version__: str
arpack_options: igraph.ARPACKOptions

class EdgeSeq:
    graph: Incomplete
    indices: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def attribute_names(self, *args, **kwargs): ...
    def find(self, *args, **kwargs): ...
    def get_attribute_values(self, *args, **kwargs): ...
    def is_all(self, *args, **kwargs): ...
    def select(self, *args, **kwargs): ...
    def set_attribute_values(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

class GraphBase:
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def Adjacency(cls, *args, **kwargs): ...
    @classmethod
    def Asymmetric_Preference(cls, *args, **kwargs): ...
    @classmethod
    def Atlas(cls, *args, **kwargs): ...
    @classmethod
    def Barabasi(cls, *args, **kwargs): ...
    @classmethod
    def Chung_Lu(cls, *args, **kwargs): ...
    @classmethod
    def De_Bruijn(cls, *args, **kwargs): ...
    @classmethod
    def Degree_Sequence(cls, *args, **kwargs): ...
    @classmethod
    def Erdos_Renyi(cls, *args, **kwargs): ...
    @classmethod
    def Establishment(cls, *args, **kwargs): ...
    @classmethod
    def Famous(cls, *args, **kwargs): ...
    @classmethod
    def Forest_Fire(cls, *args, **kwargs): ...
    @classmethod
    def Full(cls, *args, **kwargs): ...
    @classmethod
    def Full_Citation(cls, *args, **kwargs): ...
    @classmethod
    def Growing_Random(cls, *args, **kwargs): ...
    @classmethod
    def Hexagonal_Lattice(cls, *args, **kwargs): ...
    @classmethod
    def Hypercube(cls, *args, **kwargs): ...
    @classmethod
    def Isoclass(cls, *args, **kwargs): ...
    @classmethod
    def K_Regular(cls, *args, **kwargs): ...
    @classmethod
    def Kautz(cls, *args, **kwargs): ...
    @classmethod
    def LCF(cls, *args, **kwargs): ...
    @classmethod
    def Lattice(cls, *args, **kwargs): ...
    @classmethod
    def Nearest_Neighbor_Graph(cls, *args, **kwargs): ...
    @classmethod
    def Preference(cls, *args, **kwargs): ...
    @classmethod
    def Prufer(cls, *args, **kwargs): ...
    @classmethod
    def Read_DIMACS(cls, *args, **kwargs): ...
    @classmethod
    def Read_DL(cls, *args, **kwargs): ...
    @classmethod
    def Read_Edgelist(cls, *args, **kwargs): ...
    @classmethod
    def Read_GML(cls, *args, **kwargs): ...
    @classmethod
    def Read_GraphDB(cls, *args, **kwargs): ...
    @classmethod
    def Read_GraphML(cls, *args, **kwargs): ...
    @classmethod
    def Read_Lgl(cls, *args, **kwargs): ...
    @classmethod
    def Read_Ncol(cls, *args, **kwargs): ...
    @classmethod
    def Read_Pajek(cls, *args, **kwargs): ...
    @classmethod
    def Realize_Bipartite_Degree_Sequence(cls, *args, **kwargs): ...
    @classmethod
    def Realize_Degree_Sequence(cls, *args, **kwargs): ...
    @classmethod
    def Recent_Degree(cls, *args, **kwargs): ...
    @classmethod
    def Ring(cls, *args, **kwargs): ...
    @classmethod
    def SBM(cls, *args, **kwargs): ...
    @classmethod
    def Star(cls, *args, **kwargs): ...
    @classmethod
    def Static_Fitness(cls, *args, **kwargs): ...
    @classmethod
    def Static_Power_Law(cls, *args, **kwargs): ...
    @classmethod
    def Tree(cls, *args, **kwargs): ...
    @classmethod
    def Tree_Game(cls, *args, **kwargs): ...
    @classmethod
    def Triangular_Lattice(cls, *args, **kwargs): ...
    @classmethod
    def Watts_Strogatz(cls, *args, **kwargs): ...
    def add_edges(self, *args, **kwargs): ...
    def add_vertices(self, *args, **kwargs): ...
    def all_minimal_st_separators(self, *args, **kwargs): ...
    def all_st_cuts(self, *args, **kwargs): ...
    def all_st_mincuts(self, *args, **kwargs): ...
    def are_adjacent(self, *args, **kwargs): ...
    def articulation_points(self, *args, **kwargs): ...
    def assortativity(self, *args, **kwargs): ...
    def assortativity_degree(self) -> Any: ...
    def assortativity_nominal(self, *args, **kwargs): ...
    def attributes(self, *args, **kwargs): ...
    def authority_score(self, *args, **kwargs): ...
    def automorphism_group(self, *args, **kwargs): ...
    def average_path_length(self, *args, **kwargs): ...
    def betweenness(self, *args, **kwargs): ...
    def bfs(self, *args, **kwargs): ...
    def bfsiter(self, *args, **kwargs): ...
    def bibcoupling(self, *args, **kwargs): ...
    def biconnected_components(self, *args, **kwargs): ...
    def bipartite_projection(self) -> Any: ...
    def bipartite_projection_size(self) -> Any: ...
    def bridges(self, *args, **kwargs): ...
    def canonical_permutation(self, *args, **kwargs): ...
    def chordal_completion(self, *args, **kwargs): ...
    def clique_number(self, *args, **kwargs): ...
    def cliques(self, *args, **kwargs): ...
    def closeness(self, *args, **kwargs): ...
    def cocitation(self, *args, **kwargs): ...
    def cohesive_blocks(self, *args, **kwargs): ...
    def community_edge_betweenness(self, *args, **kwargs): ...
    def community_fastgreedy(self, *args, **kwargs): ...
    def community_fluid_communities(self, *args, **kwargs): ...
    def community_infomap(self, *args, **kwargs): ...
    def community_label_propagation(self, *args, **kwargs): ...
    def community_leading_eigenvector(self, *args, **kwargs): ...
    def community_leiden(self, *args, **kwargs): ...
    def community_multilevel(self, *args, **kwargs): ...
    def community_optimal_modularity(self, *args, **kwargs): ...
    def community_spinglass(self, *args, **kwargs): ...
    def community_voronoi(self, *args, **kwargs): ...
    def community_walktrap(self, *args, **kwargs): ...
    def complementer(self, *args, **kwargs): ...
    def compose(self, *args, **kwargs): ...
    def connected_components(self, *args, **kwargs): ...
    def constraint(self, *args, **kwargs): ...
    def contract_vertices(self, *args, **kwargs): ...
    def convergence_degree(self, *args, **kwargs): ...
    def convergence_field_size(self, *args, **kwargs): ...
    def copy(self, *args, **kwargs): ...
    def coreness(self, shellindex) -> Any: ...
    def count_automorphisms(self, *args, **kwargs): ...
    def count_isomorphisms_vf2(self, *args, **kwargs): ...
    def count_multiple(self, *args, **kwargs): ...
    def count_subisomorphisms_vf2(self, *args, **kwargs): ...
    def decompose(self, *args, **kwargs): ...
    def degree(self, *args, **kwargs): ...
    def delete_edges(self, *args, **kwargs): ...
    def delete_vertices(self, *args, **kwargs): ...
    def density(self, *args, **kwargs): ...
    def dfsiter(self, *args, **kwargs): ...
    def diameter(self, *args, **kwargs): ...
    def difference(self, *args, **kwargs): ...
    def distances(self, *args, **kwargs): ...
    def diversity(self, *args, **kwargs): ...
    def dominator(self, *args, **kwargs): ...
    def dyad_census(self, *args, **kwargs): ...
    def eccentricity(self, *args, **kwargs): ...
    def ecount(self, *args, **kwargs): ...
    def edge_attributes(self, *args, **kwargs): ...
    def edge_betweenness(self, *args, **kwargs): ...
    def edge_connectivity(self, *args, **kwargs): ...
    def eigen_adjacency(self, *args, **kwargs): ...
    def eigenvector_centrality(self, *args, **kwargs): ...
    def farthest_points(self, *args, **kwargs): ...
    def feedback_arc_set(self, *args, **kwargs): ...
    def feedback_vertex_set(self, *args, **kwargs): ...
    def fundamental_cycles(self, *args, **kwargs): ...
    def get_adjacency(self, *args, **kwargs): ...
    def get_all_shortest_paths(self, *args, **kwargs): ...
    def get_biadjacency(self) -> Any: ...
    def get_diameter(self, *args, **kwargs): ...
    def get_edgelist(self, *args, **kwargs): ...
    def get_eid(self, *args, **kwargs): ...
    def get_eids(self, *args, **kwargs): ...
    def get_isomorphisms_vf2(self, *args, **kwargs): ...
    def get_k_shortest_paths(self, *args, **kwargs): ...
    def get_shortest_path(self, *args, **kwargs): ...
    def get_shortest_path_astar(self, *args, **kwargs): ...
    def get_shortest_paths(self, *args, **kwargs): ...
    def get_subisomorphisms_lad(self, *args, **kwargs): ...
    def get_subisomorphisms_vf2(self, *args, **kwargs): ...
    def girth(self, *args, **kwargs): ...
    def gomory_hu_tree(self) -> Any: ...
    def harmonic_centrality(self, *args, **kwargs): ...
    def has_multiple(self, *args, **kwargs): ...
    def hub_score(self, *args, **kwargs): ...
    def incident(self, *args, **kwargs): ...
    def independence_number(self, *args, **kwargs): ...
    def independent_vertex_sets(self, *args, **kwargs): ...
    def induced_subgraph(self, *args, **kwargs): ...
    def is_acyclic(self, *args, **kwargs): ...
    def is_biconnected(self, *args, **kwargs): ...
    def is_bipartite(self, *args, **kwargs): ...
    def is_chordal(self, *args, **kwargs): ...
    def is_clique(self, *args, **kwargs): ...
    def is_complete(self, *args, **kwargs): ...
    def is_connected(self, *args, **kwargs): ...
    def is_dag(self, *args, **kwargs): ...
    def is_directed(self, *args, **kwargs): ...
    def is_independent_vertex_set(self, *args, **kwargs): ...
    def is_loop(self, *args, **kwargs): ...
    def is_minimal_separator(self, *args, **kwargs): ...
    def is_multiple(self, *args, **kwargs): ...
    def is_mutual(self, *args, **kwargs): ...
    def is_separator(self, *args, **kwargs): ...
    def is_simple(self, *args, **kwargs): ...
    def is_tree(self, *args, **kwargs): ...
    def isoclass(self, *args, **kwargs): ...
    def isomorphic(self, *args, **kwargs): ...
    def isomorphic_bliss(self, *args, **kwargs): ...
    def isomorphic_vf2(self, *args, **kwargs): ...
    def knn(self, *args, **kwargs): ...
    def laplacian(self, *args, **kwargs): ...
    def largest_cliques(self, *args, **kwargs): ...
    def largest_independent_vertex_sets(self, *args, **kwargs): ...
    def layout_bipartite(self, *args, **kwargs): ...
    def layout_circle(self, *args, **kwargs): ...
    def layout_davidson_harel(self, *args, **kwargs): ...
    def layout_drl(self, *args, **kwargs): ...
    def layout_fruchterman_reingold(self, *args, **kwargs): ...
    def layout_graphopt(self, *args, **kwargs): ...
    def layout_grid(self, *args, **kwargs): ...
    def layout_kamada_kawai(self, *args, **kwargs): ...
    def layout_lgl(self, *args, **kwargs): ...
    def layout_mds(self, *args, **kwargs): ...
    def layout_random(self, *args, **kwargs): ...
    def layout_reingold_tilford(self, *args, **kwargs): ...
    def layout_reingold_tilford_circular(self, *args, **kwargs): ...
    def layout_star(self, *args, **kwargs): ...
    def layout_umap(self, weights=...) -> Any: ...
    def linegraph(self, *args, **kwargs): ...
    def list_triangles(self, *args, **kwargs): ...
    def maxdegree(self, *args, **kwargs): ...
    def maxflow(self, *args, **kwargs): ...
    def maxflow_value(self, *args, **kwargs): ...
    def maximal_cliques(self, *args, **kwargs): ...
    def maximal_independent_vertex_sets(self, *args, **kwargs): ...
    def maximum_cardinality_search(self, *args, **kwargs): ...
    def mean_degree(self, *args, **kwargs): ...
    def mincut(self, *args, **kwargs): ...
    def mincut_value(self, *args, **kwargs): ...
    def minimum_cycle_basis(self, *args, **kwargs): ...
    def minimum_size_separators(self, *args, **kwargs): ...
    def modularity(self, *args, **kwargs): ...
    def modularity_matrix(self, *args, **kwargs): ...
    def motifs_randesu(self, *args, **kwargs): ...
    def motifs_randesu_estimate(self, *args, **kwargs): ...
    def motifs_randesu_no(self, *args, **kwargs): ...
    def neighborhood(self, *args, **kwargs): ...
    def neighborhood_size(self, *args, **kwargs): ...
    def neighbors(self, *args, **kwargs): ...
    def path_length_hist(self, *args, **kwargs): ...
    def permute_vertices(self, *args, **kwargs): ...
    def personalized_pagerank(self, *args, **kwargs): ...
    def radius(self, *args, **kwargs): ...
    def random_walk(self, *args, **kwargs): ...
    def reciprocity(self, *args, **kwargs): ...
    def reverse_edges(self, *args, **kwargs): ...
    def rewire_edges(self, *args, **kwargs): ...
    def similarity_dice(self, *args, **kwargs): ...
    def similarity_inverse_log_weighted(self, *args, **kwargs): ...
    def similarity_jaccard(self, *args, **kwargs): ...
    def simple_cycles(self, *args, **kwargs): ...
    @overload
    def simplify(self, combine_edges=...) -> Any: ...
    @overload
    def simplify(self, combine_edges=...) -> Any: ...
    @overload
    def simplify(self, combine_edges=...) -> Any: ...
    @overload
    def simplify(self, combine_edges=...) -> Any: ...
    def st_mincut(self, *args, **kwargs): ...
    def strength(self, weighteddegree) -> Any: ...
    def subcomponent(self, *args, **kwargs): ...
    def subgraph_edges(self, *args, **kwargs): ...
    def subisomorphic_lad(self, *args, **kwargs): ...
    def subisomorphic_vf2(self, *args, **kwargs): ...
    def to_directed(self, *args, **kwargs): ...
    def to_prufer(self, *args, **kwargs): ...
    def to_undirected(self, *args, **kwargs): ...
    def topological_sorting(self, *args, **kwargs): ...
    def transitivity_avglocal_undirected(self, *args, **kwargs): ...
    def transitivity_local_undirected(self, *args, **kwargs): ...
    def transitivity_undirected(self, *args, **kwargs): ...
    def triad_census(self, *args, **kwargs): ...
    def unfold_tree(self, *args, **kwargs): ...
    def vcount(self, *args, **kwargs): ...
    def vertex_attributes(self, *args, **kwargs): ...
    def vertex_coloring_greedy(self, *args, **kwargs): ...
    def vertex_connectivity(self, *args, **kwargs): ...
    def write_dimacs(self, *args, **kwargs): ...
    def write_dot(self, *args, **kwargs): ...
    def write_edgelist(self, *args, **kwargs): ...
    def write_gml(self, *args, **kwargs): ...
    def write_graphml(self, *args, **kwargs): ...
    def write_leda(self, *args, **kwargs): ...
    def write_lgl(self, *args, **kwargs): ...
    def write_ncol(self, *args, **kwargs): ...
    def write_pajek(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __invert__(self): ...
    def __setitem__(self, index, object) -> None: ...

class InternalError(Exception): ...

class VertexSeq:
    graph: Incomplete
    indices: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def attribute_names(self, *args, **kwargs): ...
    def find(self, *args, **kwargs): ...
    def get_attribute_values(self, *args, **kwargs): ...
    def select(self, *args, **kwargs): ...
    def set_attribute_values(self, *args, **kwargs): ...
    def __delitem__(self, other) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, object) -> None: ...

def community_to_membership(*args, **kwargs): ...
def convex_hull(*args, **kwargs): ...
def is_bigraphical(*args, **kwargs): ...
def is_degree_sequence(*args, **kwargs): ...
def is_graphical(*args, **kwargs): ...
def is_graphical_degree_sequence(*args, **kwargs): ...
def set_progress_handler(*args, **kwargs): ...
def set_random_number_generator(*args, **kwargs): ...
def set_status_handler(*args, **kwargs): ...
def umap_compute_weights(graph, dist) -> Any: ...
