__all__ = ['_get_adjacency', '_get_adjacency_sparse', '_get_adjlist', '_get_biadjacency', '_get_inclist']

def _get_adjacency(self, type=..., attribute=None, default: int = 0, eids: bool = False): ...
def _get_adjacency_sparse(self, attribute=None): ...
def _get_adjlist(self, mode: str = 'out', loops: str = 'twice', multiple: bool = True): ...
def _get_biadjacency(graph, types: str = 'type', *args, **kwds): ...
def _get_inclist(graph, mode: str = 'out', loops: str = 'twice'): ...
