__all__ = ['_count_automorphisms_vf2', '_get_automorphisms_vf2']

def _count_automorphisms_vf2(graph, color=None, edge_color=None, node_compat_fn=None, edge_compat_fn=None): ...
def _get_automorphisms_vf2(graph, color=None, edge_color=None, node_compat_fn=None, edge_compat_fn=None): ...
