from igraph._igraph import GraphBase as GraphBase, community_to_membership as community_to_membership
from igraph.configuration import Configuration as Configuration
from igraph.datatypes import UniqueIdGenerator as UniqueIdGenerator
from igraph.drawing.cairo.dendrogram import CairoDendrogramDrawer as CairoDendrogramDrawer
from igraph.drawing.colors import ClusterColoringPalette as ClusterColoringPalette
from igraph.drawing.matplotlib.dendrogram import MatplotlibDendrogramDrawer as MatplotlibDendrogramDrawer
from igraph.statistics import Histogram as Histogram
from igraph.utils import deprecated as deprecated

class Clustering:
    def __init__(self, membership, params=None) -> None: ...
    def __getitem__(self, idx): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def as_cover(self): ...
    def compare_to(self, other, *args, **kwds): ...
    @property
    def membership(self): ...
    @property
    def n(self): ...
    def size(self, idx): ...
    def sizes(self, *args): ...
    def size_histogram(self, bin_width: int = 1): ...
    def summary(self, verbosity: int = 0, width=None): ...

class VertexClustering(Clustering):
    def __init__(self, graph, membership=None, modularity=None, params=None, modularity_params=None) -> None: ...
    @classmethod
    def FromAttribute(cls, graph, attribute, intervals=None, params=None): ...
    def as_cover(self): ...
    def cluster_graph(self, combine_vertices=None, combine_edges=None): ...
    def crossing(self): ...
    @property
    def modularity(self): ...
    q = modularity
    @property
    def graph(self): ...
    def recalculate_modularity(self): ...
    def subgraph(self, idx): ...
    def subgraphs(self): ...
    def giant(self): ...
    def __plot__(self, backend, context, *args, **kwds): ...

class Dendrogram:
    def __init__(self, merges) -> None: ...
    def format(self, format: str = 'newick'): ...
    def summary(self, verbosity: int = 0, max_leaf_count: int = 40): ...
    def __plot__(self, backend, context, *args, **kwds) -> None: ...
    @property
    def merges(self): ...
    @property
    def names(self): ...
    @names.setter
    def names(self, items) -> None: ...

class VertexDendrogram(Dendrogram):
    def __init__(self, graph, merges, optimal_count=None, modularity_params=None) -> None: ...
    def as_clustering(self, n=None): ...
    @property
    def optimal_count(self): ...
    @optimal_count.setter
    def optimal_count(self, value) -> None: ...
    def __plot__(self, backend, context, *args, **kwds): ...

class Cover:
    def __init__(self, clusters, n: int = 0) -> None: ...
    def __getitem__(self, index): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    @property
    def membership(self): ...
    @property
    def n(self): ...
    def size(self, idx): ...
    def sizes(self, *args): ...
    def size_histogram(self, bin_width: int = 1): ...
    def summary(self, verbosity: int = 0, width=None): ...

class VertexCover(Cover):
    def __init__(self, graph, clusters=None) -> None: ...
    def crossing(self): ...
    @property
    def graph(self): ...
    def subgraph(self, idx): ...
    def subgraphs(self): ...
    def __plot__(self, backend, context, *args, **kwds): ...

class CohesiveBlocks(VertexCover):
    def __init__(self, graph, blocks=None, cohesion=None, parent=None) -> None: ...
    def cohesion(self, idx): ...
    def cohesions(self): ...
    def hierarchy(self): ...
    def max_cohesion(self, idx): ...
    def max_cohesions(self): ...
    def parent(self, idx): ...
    def parents(self): ...
    def __plot__(self, backend, context, *args, **kwds): ...

def compare_communities(comm1, comm2, method: str = 'vi', remove_none: bool = False): ...
def split_join_distance(comm1, comm2, remove_none: bool = False): ...
