from typing import IO

class Configuration:
    class Types:
        @staticmethod
        def setboolean(obj, section, key, value) -> None: ...
        @staticmethod
        def setint(obj, section, key, value) -> None: ...
        @staticmethod
        def setfloat(obj, section, key, value) -> None: ...
    def __init__(self, filename=None) -> None: ...
    @property
    def filename(self) -> str | None: ...
    def __contains__(self, item: str) -> bool: ...
    def __getitem__(self, item: str): ...
    def __setitem__(self, item: str, value): ...
    def __delitem__(self, item: str): ...
    def has_key(self, item: str) -> bool: ...
    def load(self, stream=None) -> None: ...
    def save(self, stream: str | IO[str] | None = None): ...
    @classmethod
    def instance(cls): ...

def get_user_config_file() -> str: ...
def init() -> Configuration: ...
