from igraph._igraph import GraphBase as GraphBase
from igraph.clustering import VertexClustering as VertexClustering

class Cut(VertexClustering):
    def __init__(self, graph, value=None, cut=None, partition=None, partition2=None) -> None: ...
    @property
    def es(self): ...
    @property
    def partition(self): ...
    @property
    def cut(self): ...
    @property
    def value(self): ...

class Flow(Cut):
    def __init__(self, graph, value, flow, cut, partition) -> None: ...
    @property
    def flow(self): ...
