from _typeshed import Incomplete

__all__ = ['Matrix']

class Matrix:
    data: Incomplete
    def __init__(self, data=None) -> None: ...
    @classmethod
    def Fill(cls, value, *args): ...
    @classmethod
    def Zero(cls, *args): ...
    @classmethod
    def Identity(cls, *args): ...
    @property
    def shape(self): ...
    def __add__(self, other): ...
    def __eq__(self, other): ...
    def __getitem__(self, i): ...
    def __hash__(self): ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __len__(self) -> int: ...
    def __ne__(self, other): ...
    def __setitem__(self, i, value) -> None: ...
    def __sub__(self, other): ...
    def __iter__(self): ...
    def __plot__(self, backend, context, **kwds) -> None: ...
    def min(self, dim=None): ...
    def max(self, dim=None): ...

class DyadCensus(tuple):
    def __getitem__(self, idx): ...
    def __getattr__(self, attr): ...
    def as_dict(self): ...

class TriadCensus(tuple):
    def __getitem__(self, idx): ...
    def __getattr__(self, attr): ...

class UniqueIdGenerator:
    def __init__(self, id_generator=None, initial=None) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value) -> None: ...
    def __len__(self) -> int: ...
    def reverse_dict(self): ...
    def values(self): ...
    add = __getitem__
