from _typeshed import Incomplete

__all__ = ['Layout', 'align_layout', '_layout', '_layout_auto', '_layout_sugiyama', '_layout_method_wrapper', '_3d_version_for', '_layout_mapping']

class Layout:
    edge_routing: Incomplete
    def __init__(self, coords=None, dim=None) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx): ...
    def __setitem__(self, idx, value) -> None: ...
    def __delitem__(self, idx) -> None: ...
    def __copy__(self): ...
    @property
    def dim(self): ...
    @property
    def coords(self): ...
    def append(self, value) -> None: ...
    def mirror(self, dim) -> None: ...
    def rotate(self, angle, dim1: int = 0, dim2: int = 1, **kwds) -> None: ...
    def scale(self, *args, **kwds) -> None: ...
    def translate(self, *args, **kwds) -> None: ...
    def to_radial(self, min_angle: int = 100, max_angle: int = 80, min_radius: float = 0.0, max_radius: float = 1.0) -> None: ...
    def transform(self, function, *args, **kwds) -> None: ...
    def centroid(self): ...
    def boundaries(self, border: int = 0): ...
    def bounding_box(self, border: int = 0): ...
    def center(self, *args, **kwds) -> None: ...
    def copy(self): ...
    def fit_into(self, bbox, keep_aspect_ratio: bool = True) -> None: ...

def _layout(graph, layout=None, *args, **kwds): ...
def align_layout(graph, layout): ...
def _layout_auto(graph, *args, **kwds): ...
def _layout_sugiyama(graph, layers=None, weights=None, hgap: int = 1, vgap: int = 1, maxiter: int = 100): ...
def _layout_method_wrapper(func): ...
def _3d_version_for(func): ...

_layout_mapping: Incomplete
