from igraph._igraph import Vertex as Vertex

class Matching:
    def __init__(self, graph, matching, types=None) -> None: ...
    def __len__(self) -> int: ...
    def edges(self): ...
    @property
    def graph(self): ...
    def is_maximal(self): ...
    def is_matched(self, vertex): ...
    def match_of(self, vertex): ...
    @property
    def matching(self): ...
    @matching.setter
    def matching(self, value) -> None: ...
    @property
    def types(self): ...
    @types.setter
    def types(self, value) -> None: ...
