from igraph._igraph import EdgeSeq as _EdgeSeq, VertexSeq as _VertexSeq

class VertexSeq(_VertexSeq):
    def attributes(self): ...
    def find(self, *args, **kwds): ...
    def select(self, *args, **kwds): ...
    def __call__(self, *args, **kwds): ...

class EdgeSeq(_EdgeSeq):
    def attributes(self): ...
    def find(self, *args, **kwds): ...
    def select(self, *args, **kwds): ...
    def __call__(self, *args, **kwds): ...
