from igraph._igraph import ADJ_DIRECTED as ADJ_DIRECTED, ADJ_LOWER as ADJ_LOWER, ADJ_MAX as ADJ_MAX, ADJ_MIN as ADJ_MIN, ADJ_PLUS as ADJ_PLUS, ADJ_UNDIRECTED as ADJ_UNDIRECTED, ADJ_UPPER as ADJ_UPPER

__docformat__: str
