from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['FittedPowerLaw', 'Histogram', 'RunningMean', 'mean', 'median', 'percentile', 'quantile', 'power_law_fit']

class FittedPowerLaw:
    continuous: Incomplete
    xmin: Incomplete
    alpha: Incomplete
    L: Incomplete
    D: Incomplete
    p: Incomplete
    def __init__(self, continuous, alpha, xmin, L, D, p) -> None: ...
    def summary(self, significance: float = 0.05): ...

class Histogram:
    def __init__(self, bin_width: int = 1, data=None) -> None: ...
    @property
    def n(self): ...
    @property
    def mean(self): ...
    @property
    def sd(self): ...
    @property
    def var(self): ...
    def add(self, num, repeat: int = 1) -> None: ...
    def add_many(self, data) -> None: ...
    __lshift__ = add_many
    def clear(self) -> None: ...
    def bins(self) -> Generator[Incomplete]: ...
    def __plot__(self, backend, context, **kwds) -> None: ...
    def to_string(self, max_width: int = 78, show_bars: bool = True, show_counts: bool = True): ...

class RunningMean:
    def __init__(self, items=None, n: float = 0.0, mean: float = 0.0, sd: float = 0.0) -> None: ...
    def add(self, value, repeat: int = 1) -> None: ...
    def add_many(self, values) -> None: ...
    def clear(self) -> None: ...
    @property
    def result(self): ...
    @property
    def mean(self): ...
    @property
    def sd(self): ...
    @property
    def var(self): ...
    __lshift__ = add_many
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __complex__(self) -> complex: ...
    def __len__(self) -> int: ...

def mean(xs): ...
def median(xs, sort: bool = True): ...
def percentile(xs, p=(25, 50, 75), sort: bool = True): ...
def power_law_fit(data, xmin=None, method: str = 'auto', p_precision: float = 0.01): ...
def quantile(xs, q=(0.25, 0.5, 0.75), sort: bool = True): ...
