from _typeshed import Incomplete
from collections.abc import Generator, MutableMapping
from contextlib import contextmanager

__all__ = ['dbl_epsilon', 'deprecated', 'multidict', 'named_temporary_file', 'numpy_to_contiguous_memoryview', 'rescale', 'safemin', 'safemax']

def deprecated(message) -> None: ...
@contextmanager
def named_temporary_file(*args, **kwds) -> Generator[Incomplete]: ...
def numpy_to_contiguous_memoryview(obj): ...
def rescale(values, out_range=(0.0, 1.0), in_range=None, clamp: bool = False, scale=None): ...

class multidict(MutableMapping):
    def __init__(self, *args, **kwds) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __setitem__(self, key, value) -> None: ...
    def add(self, key, value) -> None: ...
    def clear(self) -> None: ...
    def get(self, key, default=None): ...
    def getlist(self, key): ...
    def iterlists(self): ...
    def lists(self): ...
    def update(self, arg, **kwds) -> None: ...

def safemax(iterable, default: int = 0): ...
def safemin(iterable, default: int = 0): ...
def dbl_epsilon(): ...

dbl_epsilon: Incomplete
