from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['GephiConnection', 'GephiGraphStreamer', 'GephiGraphStreamingAPIFormat']

class GephiConnection:
    def __init__(self, url=None, host: str = '127.0.0.1', port: int = 8080, workspace: int = 1) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def flush(self): ...
    @property
    def url(self): ...
    @url.setter
    def url(self, value) -> None: ...
    def write(self, data) -> None: ...

class GephiGraphStreamingAPIFormat:
    def get_add_node_event(self, identifier, attributes=None): ...
    def get_add_edge_event(self, identifier, source, target, directed, attributes=None): ...
    def get_change_node_event(self, identifier, attributes): ...
    def get_change_edge_event(self, identifier, attributes): ...
    def get_delete_node_event(self, identifier): ...
    def get_delete_edge_event(self, identifier): ...

class GephiGraphStreamer:
    encoder: Incomplete
    format: Incomplete
    def __init__(self, encoder=None) -> None: ...
    def iterjsonobj(self, graph) -> Generator[Incomplete]: ...
    def post(self, graph, destination, encoder=None) -> None: ...
    def send_event(self, event, destination, encoder=None, flush: bool = True) -> None: ...
